# Generated by Django 2.0.5 on 2018-06-18 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Theatre',
            new_name='MovieReview',
        ),
    ]
