# Generated by Django 2.0.5 on 2018-06-18 18:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0002_auto_20180618_2346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviereview',
            old_name='name',
            new_name='movie_name',
        ),
        migrations.AddField(
            model_name='moviereview',
            name='director',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='moviereview',
            name='genre',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='moviereview',
            name='release_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moviereview',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
