# Generated by Django 2.0.5 on 2018-06-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0003_auto_20180619_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviereview',
            name='slugs',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
