# Generated by Django 2.0.5 on 2018-06-24 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theatre', '0004_moviereview_slugs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviereview',
            old_name='slugs',
            new_name='slug',
        ),
    ]
